services:
  traefik:
    image: traefik:v3.1
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80" # HTTP
      - "8081:8080" # Dashboard
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--api.dashboard=true"
      - "--api.insecure=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy
    labels:
      - "traefik.http.serversTransports.portainer-transport.insecureSkipVerify=true"
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  proxy:
    external: true
