services:
  web:
    image: nginx:alpine
    container_name: demo-nginx
    restart: unless-stopped
    volumes:
      - ./html:/usr/share/nginx/html:ro
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.demo-nginx.rule=Host(`nginx.localhost`)"
      - "traefik.http.routers.demo-nginx.entrypoints=web"
      - "traefik.http.services.demo-nginx.loadbalancer.server.port=80"
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  proxy:
    external: true
