services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks: [proxy]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dozzle.rule=Host(`dozzle.localhost`)"
      - "traefik.http.routers.dozzle.entrypoints=web"
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  proxy:
    external: true
