services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    command:
      - -H
      - unix:///var/run/docker.sock
      - --http-enabled
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks: [proxy]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.localhost`)"
      - "traefik.http.routers.portainer.entrypoints=web"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "com.centurylinklabs.watchtower.enable=true"
volumes:
  portainer_data:
networks:
  proxy:
    external: true
