services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: unless-stopped
    volumes:
      - uptime-kuma-data:/app/data
    networks: [proxy]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptime.rule=Host(`uptime.localhost`)"
      - "traefik.http.routers.uptime.entrypoints=web"
      - "com.centurylinklabs.watchtower.enable=true"

volumes:
  uptime-kuma-data:

networks:
  proxy:
    external: true
