services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: myapp
    networks:
      - proxy
    volumes:
      - postgres_data:/var/lib/postgresql/data
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    depends_on:
      - db
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`adminer.localhost`)"
      - "traefik.http.routers.adminer.entrypoints=web"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"
      - "com.centurylinklabs.watchtower.enable=true"

volumes:
  postgres_data:

networks:
  proxy:
    external: true
